# Site
name: "vagasbrasil"
title: "vagasbrasil"
description: "Blog com intuito de divulgar vagas de forma acessivel"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: https://vagasbrasil.pages.dev
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  luiz:
    name: Luiz Gabriel
    display_name: Luiz Gabriel

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-sitemap
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
encoding: bom|utf-8



kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

comments: "disabled"
# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
encoding: utf-8
